import { connectorHttpError } from "../connectors/errors.ts";
import type { CanonicalObjectType, CanonicalRecord, ConnectorAdapter, ConnectorPage } from "../connectors/types";
export type BirdeyeCredentials = { apiKey: string; businessId: string };
async function birdeyeFetch(credentials: BirdeyeCredentials, start = 0) { const response = await fetch(`https://api.birdeye.com/resources/v1/review/businessId/${encodeURIComponent(credentials.businessId)}?${new URLSearchParams({ api_key: credentials.apiKey, sindex: String(start), count: "100" })}`, { signal: AbortSignal.timeout(15_000) }); if (!response.ok) throw connectorHttpError("birdeye", response); return response; }
export const birdeyeAdapter: ConnectorAdapter<BirdeyeCredentials> = {
  manifest: { key: "birdeye", name: "Birdeye", category: "reputation", description: "Aggregated customer reviews and ratings from Birdeye.", authStrategy: "api_key", capabilities: ["review.read"], verificationStatus: "contract_verified", requestable: false, docsUrl: "https://developers.birdeye.com/" },
  async testConnection(context) { try { await birdeyeFetch(context.credentials, 0); return { ok: true, detail: "Birdeye connected. Reviews and ratings are ready for the marketing dashboard.", externalAccountId: context.credentials.businessId, externalAccountName: `Birdeye ${context.credentials.businessId}` }; } catch (error) { return { ok: false, detail: error instanceof Error ? error.message : "Birdeye verification failed." }; } },
  async pullPage(context, objectType: CanonicalObjectType, cursor): Promise<ConnectorPage> { if (objectType !== "review") throw new Error(`Birdeye cannot pull ${objectType}.`); const start = typeof cursor?.start === "number" ? cursor.start : 0; const body = await (await birdeyeFetch(context.credentials, start)).json() as Record<string, unknown>[] | { reviews?: Record<string, unknown>[] }; const rows = Array.isArray(body) ? body : body.reviews ?? []; return { records: rows.map((review): CanonicalRecord => ({ objectType: "review", externalId: String(review.reviewId ?? review.id ?? ""), updatedAt: typeof review.reviewDate === "string" ? review.reviewDate : null, data: { author: review.reviewerName ?? "Customer", rating: review.rating ?? null, comment: review.comments ?? review.reviewText ?? null, source: review.sourceType ?? "birdeye", location: review.businessName ?? null, reply: review.reviewResponse ?? null }, source: review })), nextCursor: rows.length === 100 ? { start: start + 100 } : null }; },
};
