import { connectorHttpError } from "../connectors/errors.ts";
import type { CanonicalObjectType, CanonicalRecord, ConnectorAdapter, ConnectorPage } from "../connectors/types";

export type CallRailCredentials = { apiKey: string; accountId: string };
const BASE = "https://api.callrail.com/v3/a";
async function callRailFetch(credentials: CallRailCredentials, path: string) { const response = await fetch(`${BASE}${path}`, { headers: { Authorization: `Token token="${credentials.apiKey}"`, Accept: "application/json", "User-Agent": "Northstar-Connector/1.0" }, signal: AbortSignal.timeout(15_000) }); if (!response.ok) throw connectorHttpError("callrail", response); return response; }
function mapCall(source: Record<string, unknown>): CanonicalRecord { return { objectType: "lead", externalId: String(source.id ?? ""), updatedAt: (source.start_time ?? source.created_at) as string | undefined, data: { name: source.customer_name ?? "Phone lead", phone: source.customer_phone_number ?? null, title: `Call from ${source.customer_name ?? source.customer_phone_number ?? "unknown caller"}`, description: source.note ?? source.transcription ?? null, status: source.lead_status === "good_lead" ? "new" : "contacted", source: source.source_name ?? source.source ?? "callrail", campaign: source.campaign ?? null, medium: source.medium ?? "phone", answered: source.answered ?? null, duration: source.duration ?? null }, source }; }
function mapForm(source: Record<string, unknown>): CanonicalRecord { const fields = (source.form_data ?? {}) as Record<string, unknown>; return { objectType: "lead", externalId: String(source.id ?? ""), updatedAt: (source.submitted_at ?? source.created_at) as string | undefined, data: { name: fields.name ?? fields.full_name ?? "Website lead", email: fields.email ?? null, phone: fields.phone ?? null, title: `Form: ${source.form_name ?? "Website inquiry"}`, description: fields.message ?? fields.comments ?? null, status: "new", source: source.source ?? "callrail_form", campaign: source.campaign ?? null, medium: "form" }, source }; }
async function pull(credentials: CallRailCredentials, objectType: CanonicalObjectType, cursor: Record<string, unknown> | null): Promise<ConnectorPage> { if (objectType !== "lead") throw new Error(`CallRail cannot pull ${objectType}.`); const phase = cursor?.phase === "forms" ? "forms" : "calls"; const page = typeof cursor?.page === "number" ? cursor.page : 1; const path = phase === "calls" ? `/${encodeURIComponent(credentials.accountId)}/calls.json?page=${page}&per_page=100` : `/${encodeURIComponent(credentials.accountId)}/form_submissions.json?page=${page}&per_page=100`; const body = await (await callRailFetch(credentials, path)).json() as Record<string, unknown>; const rows = (phase === "calls" ? body.calls : body.form_submissions) as Record<string, unknown>[] | undefined; const totalPages = Number(body.total_pages ?? page); const nextCursor = page < totalPages ? { phase, page: page + 1 } : phase === "calls" ? { phase: "forms", page: 1 } : null; return { records: (rows ?? []).map(phase === "calls" ? mapCall : mapForm), nextCursor }; }
export const callRailAdapter: ConnectorAdapter<CallRailCredentials> = { manifest: { key: "callrail", name: "CallRail", category: "call_tracking", description: "Attributed phone calls and tracked form leads from CallRail.", authStrategy: "api_key", capabilities: ["lead.read"], verificationStatus: "contract_verified", requestable: false, docsUrl: "https://apidocs.callrail.com/", webhookEvents: ["pre_call", "post_call", "form_submission", "text_message"] }, async testConnection(context) { try { const account = await (await callRailFetch(context.credentials, `/${encodeURIComponent(context.credentials.accountId)}.json`)).json() as Record<string, unknown>; return { ok: true, detail: "CallRail connected. Calls and tracked forms are ready to sync with attribution.", externalAccountId: String(account.id ?? context.credentials.accountId), externalAccountName: String(account.name ?? "CallRail account") }; } catch (error) { return { ok: false, detail: error instanceof Error ? error.message : "CallRail verification failed." }; } }, pullPage(context, objectType, cursor) { return pull(context.credentials, objectType, cursor); } };
