import type { CanonicalObjectType, CanonicalRecord, ConnectorAdapter, ConnectorPage, ConnectorPushInput } from "../connectors/types";
import type { GoogleBusinessProfileCredentials } from "./marketing-oauth";

async function gbpFetch(credentials: GoogleBusinessProfileCredentials, path: string, init: RequestInit = {}) { const response = await fetch(`https://mybusiness.googleapis.com/v4/${path}`, { ...init, headers: { Authorization: `Bearer ${credentials.accessToken}`, "Content-Type": "application/json", ...init.headers }, signal: init.signal ?? AbortSignal.timeout(15_000) }); if (!response.ok) throw new Error(`Google Business Profile API failed (${response.status}).`); return response; }

export const googleBusinessProfileAdapter: ConnectorAdapter<GoogleBusinessProfileCredentials> = {
  manifest: { key: "google_business_profile", name: "Google Business Profile", category: "reputation", description: "Locations, customer reviews, ratings, and approved review replies.", authStrategy: "oauth2", capabilities: ["review.read", "review.update"], verificationStatus: "contract_verified", requestable: false, docsUrl: "https://developers.google.com/my-business/reference/rest" },
  async testConnection(context) { try { await gbpFetch(context.credentials, `${context.credentials.locationName}/reviews?pageSize=1`); return { ok: true, detail: "Google Business Profile connected. Reviews and ratings are ready for the marketing dashboard.", externalAccountId: context.credentials.locationName, externalAccountName: context.credentials.locationTitle }; } catch (error) { return { ok: false, detail: error instanceof Error ? error.message : "Business Profile verification failed." }; } },
  async pullPage(context, objectType: CanonicalObjectType, cursor): Promise<ConnectorPage> { if (objectType !== "review") throw new Error(`Google Business Profile cannot pull ${objectType}.`); const query = new URLSearchParams({ pageSize: "50", ...(typeof cursor?.pageToken === "string" ? { pageToken: cursor.pageToken } : {}) }); const body = await (await gbpFetch(context.credentials, `${context.credentials.locationName}/reviews?${query}`)).json() as { reviews?: Record<string, unknown>[]; nextPageToken?: string }; return { records: (body.reviews ?? []).map((review) => { const reviewer = (review.reviewer ?? {}) as Record<string, unknown>; return { objectType: "review", externalId: String(review.reviewId ?? review.name ?? ""), updatedAt: typeof review.updateTime === "string" ? review.updateTime : null, data: { author: reviewer.displayName ?? "Google user", rating: review.starRating ?? null, comment: review.comment ?? null, reply: (review.reviewReply as Record<string, unknown> | undefined)?.comment ?? null, source: "google_business_profile", location: context.credentials.locationTitle }, source: review }; }), nextCursor: body.nextPageToken ? { pageToken: body.nextPageToken } : null }; },
  async pushRecord(context, input: ConnectorPushInput) { if (input.objectType !== "review" || input.operation !== "update" || !input.externalObjectId) throw new Error(`Google Business Profile cannot ${input.operation} ${input.objectType}.`); const response = await gbpFetch(context.credentials, `${context.credentials.locationName}/reviews/${encodeURIComponent(input.externalObjectId)}/reply`, { method: "PUT", body: JSON.stringify({ comment: input.data.reply }) }); const body = await response.json() as Record<string, unknown>; return { externalObjectId: input.externalObjectId, source: body }; },
};
