import { connectorHttpError } from "../connectors/errors.ts";
import type { CanonicalObjectType, CanonicalRecord, ConnectorAdapter, ConnectorPage } from "../connectors/types";
import type { GoogleAdsCredentials } from "./marketing-oauth";

async function search(credentials: GoogleAdsCredentials, query: string, pageToken?: string) { const response = await fetch(`https://googleads.googleapis.com/v25/customers/${credentials.customerId}/googleAds:search`, { method: "POST", headers: { Authorization: `Bearer ${credentials.accessToken}`, "developer-token": credentials.developerToken, ...(credentials.managerCustomerId ? { "login-customer-id": credentials.managerCustomerId } : {}), "Content-Type": "application/json" }, body: JSON.stringify({ query, pageSize: 100, ...(pageToken ? { pageToken } : {}) }), signal: AbortSignal.timeout(20_000) }); if (!response.ok) throw connectorHttpError("google-ads", response); return response.json() as Promise<{ results?: Record<string, unknown>[]; nextPageToken?: string }>; }
function leadFields(value: unknown) { const fields = Array.isArray(value) ? value : []; return Object.fromEntries(fields.map((raw) => { const field = raw as { fieldType?: string; fieldValue?: string }; return [field.fieldType?.toLowerCase() ?? "field", field.fieldValue ?? null]; })); }

export const googleAdsAdapter: ConnectorAdapter<GoogleAdsCredentials> = {
  manifest: { key: "google_ads", name: "Google Ads and Local Services", category: "lead_source", description: "Lead forms, campaigns, spend, calls, and conversion outcomes from Google Ads.", authStrategy: "oauth2", capabilities: ["lead.read", "campaign.read"], verificationStatus: "contract_verified", requestable: false, docsUrl: "https://developers.google.com/google-ads/api/docs/start" },
  async testConnection(context) { try { await search(context.credentials, "SELECT customer.id, customer.descriptive_name FROM customer LIMIT 1"); return { ok: true, detail: "Google Ads connected. Lead forms and campaign performance are ready to sync.", externalAccountId: context.credentials.customerId, externalAccountName: `Google Ads ${context.credentials.customerId}` }; } catch (error) { return { ok: false, detail: error instanceof Error ? error.message : "Google Ads verification failed." }; } },
  async pullPage(context, objectType: CanonicalObjectType, cursor): Promise<ConnectorPage> {
    const pageToken = typeof cursor?.pageToken === "string" ? cursor.pageToken : undefined;
    if (objectType === "lead") {
      const body = await search(context.credentials, "SELECT lead_form_submission_data.id, lead_form_submission_data.submission_date_time, lead_form_submission_data.campaign, lead_form_submission_data.gclid, lead_form_submission_data.lead_form_submission_fields, lead_form_submission_data.custom_lead_form_submission_fields FROM lead_form_submission_data ORDER BY lead_form_submission_data.submission_date_time DESC", pageToken);
      const records: CanonicalRecord[] = (body.results ?? []).map((row) => { const lead = (row.leadFormSubmissionData ?? {}) as Record<string, unknown>; const fields = leadFields(lead.leadFormSubmissionFields); return { objectType: "lead", externalId: String(lead.id ?? ""), updatedAt: typeof lead.submissionDateTime === "string" ? lead.submissionDateTime : null, data: { name: fields.full_name ?? ([fields.first_name, fields.last_name].filter(Boolean).join(" ") || "Google Ads lead"), email: fields.email ?? null, phone: fields.phone_number ?? null, description: fields.message ?? null, status: "new", source: "google_ads", medium: "paid", campaign: lead.campaign ?? null, gclid: lead.gclid ?? null }, source: lead }; });
      return { records, nextCursor: body.nextPageToken ? { pageToken: body.nextPageToken } : null };
    }
    if (objectType !== "campaign") throw new Error(`Google Ads cannot pull ${objectType}.`);
    const body = await search(context.credentials, "SELECT campaign.id, campaign.name, campaign.status, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, metrics.conversions_value FROM campaign WHERE segments.date DURING LAST_30_DAYS", pageToken);
    return { records: (body.results ?? []).map((row) => { const campaign = (row.campaign ?? {}) as Record<string, unknown>; const metrics = (row.metrics ?? {}) as Record<string, unknown>; return { objectType: "campaign", externalId: String(campaign.id ?? ""), data: { name: campaign.name ?? null, status: campaign.status ?? null, impressions: metrics.impressions ?? 0, clicks: metrics.clicks ?? 0, spend: Number(metrics.costMicros ?? 0) / 1_000_000, conversions: metrics.conversions ?? 0, conversion_value: metrics.conversionsValue ?? 0, source: "google_ads" }, source: row }; }), nextCursor: body.nextPageToken ? { pageToken: body.nextPageToken } : null };
  },
};
