import { connectorHttpError } from "../connectors/errors.ts";
import type { CanonicalObjectType, CanonicalRecord, ConnectorAdapter, ConnectorPage, ConnectorPushInput } from "../connectors/types";
import { connectorPushPayload } from "../connectors/field-mappings.ts";
import type { PodiumCredentials } from "./marketing-oauth";

async function podiumFetch(credentials: PodiumCredentials, path: string, init: RequestInit = {}) { const response = await fetch(`https://api.podium.com/v4${path}`, { ...init, headers: { Authorization: `Bearer ${credentials.accessToken}`, "Content-Type": "application/json", ...init.headers }, signal: init.signal ?? AbortSignal.timeout(15_000) }); if (!response.ok) throw connectorHttpError("podium", response); return response; }

export const podiumAdapter: ConnectorAdapter<PodiumCredentials> = {
  manifest: { key: "podium", name: "Podium", category: "reputation", description: "Customer reviews from Podium.", authStrategy: "oauth2", capabilities: ["review.read"], verificationStatus: "contract_verified", requestable: false, docsUrl: "https://docs.podium.com/reference" },
  async testConnection(context) { try { await podiumFetch(context.credentials, "/reviews/summary"); return { ok: true, detail: "Podium connected. Reviews and ratings are ready for the marketing dashboard.", externalAccountName: "Podium account" }; } catch (error) { return { ok: false, detail: error instanceof Error ? error.message : "Podium verification failed." }; } },
  async pullPage(context, objectType: CanonicalObjectType, cursor): Promise<ConnectorPage> { if (objectType !== "review") throw new Error(`Podium cannot pull ${objectType}.`); const query = new URLSearchParams({ limit: "100", ...(typeof cursor?.cursor === "string" ? { cursor: cursor.cursor } : {}) }); const body = await (await podiumFetch(context.credentials, `/reviews?${query}`)).json() as { data?: Record<string, unknown>[]; metadata?: { nextCursor?: string }; nextCursor?: string }; const next = body.metadata?.nextCursor ?? body.nextCursor; return { records: (body.data ?? []).map((review): CanonicalRecord => ({ objectType: "review", externalId: String(review.uid ?? review.id ?? ""), updatedAt: typeof review.updatedAt === "string" ? review.updatedAt : null, data: { author: review.authorName ?? review.siteAuthorName ?? "Customer", rating: review.rating ?? review.ratingValue ?? null, comment: review.body ?? review.review ?? null, source: review.source ?? "podium", location: review.locationName ?? null, replied: review.hasResponse ?? null }, source: review })), nextCursor: next ? { cursor: next } : null }; },
  async pushRecord(context, input: ConnectorPushInput) { if (input.objectType !== "review" || input.operation !== "update" || !input.externalObjectId) throw new Error(`Podium cannot ${input.operation} ${input.objectType}.`); const body = await (await podiumFetch(context.credentials, `/reviews/${encodeURIComponent(input.externalObjectId)}/responses`, { method: "POST", body: JSON.stringify(connectorPushPayload(input.externalData, { body: input.data.reply })) })).json() as Record<string, unknown>; return { externalObjectId: input.externalObjectId, source: body }; },
};
