import { connectorHttpError } from "../connectors/errors.ts";
import type { CanonicalObjectType, CanonicalRecord, ConnectorAdapter, ConnectorPage, ConnectorPushInput } from "../connectors/types";
import { connectorPushPayload } from "../connectors/field-mappings.ts";
import type { SquareCredentials } from "./commerce-oauth";

const BASE = "https://connect.squareup.com";
const VERSION = "2026-07-15";
async function squareFetch(credentials: SquareCredentials, path: string, init: RequestInit = {}) { const response = await fetch(`${BASE}${path}`, { ...init, headers: { Authorization: `Bearer ${credentials.accessToken}`, "Square-Version": VERSION, "Content-Type": "application/json", ...init.headers }, signal: init.signal ?? AbortSignal.timeout(15_000) }); if (!response.ok) throw connectorHttpError("square", response); return response; }

export async function populateSquareLocation(credentials: SquareCredentials): Promise<SquareCredentials> { if (credentials.locationId) return credentials; const body = await (await squareFetch(credentials, "/v2/locations")).json() as { locations?: Record<string, unknown>[] }; const location = body.locations?.find((item) => item.status === "ACTIVE") ?? body.locations?.[0]; if (!location?.id) throw new Error("Square did not return a business location."); return { ...credentials, locationId: String(location.id) }; }

function mapCustomer(source: Record<string, unknown>): CanonicalRecord { return { objectType: "customer", externalId: String(source.id ?? ""), updatedAt: source.updated_at as string | undefined, data: { name: source.company_name ?? ([source.given_name, source.family_name].filter(Boolean).join(" ") || null), first_name: source.given_name ?? null, last_name: source.family_name ?? null, email: source.email_address ?? null, phone: source.phone_number ?? null }, source }; }
function mapInvoice(source: Record<string, unknown>): CanonicalRecord { const recipient = source.primary_recipient as Record<string, unknown> | undefined; return { objectType: "invoice", externalId: String(source.id ?? ""), updatedAt: source.updated_at as string | undefined, data: { number: source.invoice_number ?? null, customer_id: recipient?.customer_id ?? null, status: source.status ?? null, title: source.title ?? null, amount_due: (source.next_payment_amount_money as Record<string, unknown> | undefined)?.amount ?? null, public_url: source.public_url ?? null }, source }; }
function mapPayment(source: Record<string, unknown>): CanonicalRecord { return { objectType: "payment", externalId: String(source.id ?? ""), updatedAt: source.updated_at as string | undefined, data: { customer_id: source.customer_id ?? null, amount: (source.amount_money as Record<string, unknown> | undefined)?.amount ?? null, currency: (source.amount_money as Record<string, unknown> | undefined)?.currency ?? null, status: source.status ?? null, source_type: source.source_type ?? null }, source }; }

async function pull(rawCredentials: SquareCredentials, objectType: CanonicalObjectType, cursor: Record<string, unknown> | null): Promise<ConnectorPage> { const credentials = await populateSquareLocation(rawCredentials); const after = typeof cursor?.after === "string" ? cursor.after : null; const path = objectType === "customer" ? `/v2/customers?limit=100${after ? `&cursor=${encodeURIComponent(after)}` : ""}` : objectType === "payment" ? `/v2/payments?limit=100${after ? `&cursor=${encodeURIComponent(after)}` : ""}` : objectType === "invoice" ? `/v2/invoices?location_id=${encodeURIComponent(credentials.locationId!)}&limit=100${after ? `&cursor=${encodeURIComponent(after)}` : ""}` : null; if (!path) throw new Error(`Square cannot pull ${objectType}.`); const body = await (await squareFetch(credentials, path)).json() as Record<string, unknown>; const rows = (objectType === "customer" ? body.customers : objectType === "payment" ? body.payments : body.invoices) as Record<string, unknown>[] | undefined; const mapper = objectType === "customer" ? mapCustomer : objectType === "payment" ? mapPayment : mapInvoice; return { records: (rows ?? []).map(mapper), nextCursor: typeof body.cursor === "string" ? { after: body.cursor } : null }; }

async function push(rawCredentials: SquareCredentials, input: ConnectorPushInput) { const credentials = await populateSquareLocation(rawCredentials); if (input.objectType === "customer" && input.operation === "create") { const body = connectorPushPayload(input.externalData, { idempotency_key: input.idempotencyKey, given_name: input.data.first_name ?? undefined, family_name: input.data.last_name ?? undefined, company_name: input.data.name ?? undefined, email_address: input.data.email ?? undefined, phone_number: input.data.phone ?? undefined, reference_id: input.nativeObjectId }); const created = await (await squareFetch(credentials, "/v2/customers", { method: "POST", body: JSON.stringify(body) })).json() as { customer?: Record<string, unknown> }; return { externalObjectId: String(created.customer?.id ?? ""), source: created.customer }; } if (input.objectType === "payment" && input.operation === "create") { const amount = Number(input.data.amount ?? 0); if (!Number.isInteger(amount) || amount < 1) throw new Error("Square payment link amount must be an integer in cents."); const body = connectorPushPayload(input.externalData, { idempotency_key: input.idempotencyKey, quick_pay: { name: String(input.data.description ?? "Service payment"), price_money: { amount, currency: String(input.data.currency ?? "USD").toUpperCase() }, location_id: credentials.locationId } }); const created = await (await squareFetch(credentials, "/v2/online-checkout/payment-links", { method: "POST", body: JSON.stringify(body) })).json() as { payment_link?: Record<string, unknown> }; return { externalObjectId: String(created.payment_link?.id ?? ""), source: created.payment_link }; } throw new Error(`Square cannot ${input.operation} ${input.objectType}.`); }

export const squareAdapter: ConnectorAdapter<SquareCredentials> = { manifest: { key: "square", name: "Square", category: "payments", description: "Customers, invoices, payments from Square.", authStrategy: "oauth2", capabilities: ["customer.read", "invoice.read", "payment.read"], verificationStatus: "contract_verified", requestable: false, docsUrl: "https://developer.squareup.com/reference/square" }, async testConnection(context) { try { const credentials = await populateSquareLocation(context.credentials); const body = await (await squareFetch(credentials, "/v2/merchants/me")).json() as { merchant?: Record<string, unknown> }; return { ok: true, detail: "Square connected. Customers, invoices, payments are ready.", externalAccountId: credentials.merchantId, externalAccountName: String(body.merchant?.business_name ?? "Square business") }; } catch (error) { return { ok: false, detail: error instanceof Error ? error.message : "Square verification failed." }; } }, pullPage(context, objectType, cursor) { return pull(context.credentials, objectType, cursor); }, pushRecord(context, input) { return push(context.credentials, input); } };
